# Ten app phai unique tren Fly.io - doi neu bi trung
app = 'chatbot-download-video-fb'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  DOWNLOAD_DIR = '/tmp/downloads'

[deploy]
  strategy = 'immediate'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  count = 1
