services:
  - type: web
    name: chatbot-download-video-fb
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: RENDER
        value: "true"
